import { ApartmentTypes } from "@/interface/apartments";
import { DestinationType } from "@/interface/destination";

export const destinations: DestinationType[] = [
	{
		city: "Montmarte",
		country: "France",
		imageUrl: "/images/montmarte-france.jpg",
		rating: 4,
		text: "Visiting the best tourist areas chosen by the audience",
		amount: 4500000,
	},
	{
		city: "Istanbul",
		country: "Turkey",
		imageUrl: "/images/istanbul-turkey.jpg",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 6500000,
	},
	{
		city: "London",
		country: "UK",
		imageUrl: "/images/london_uk.webp",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 2500000,
	},
	{
		city: "Montmarte",
		country: "France",
		imageUrl: "/images/montmarte-france.jpg",
		rating: 4,
		text: "Visiting the best tourist areas chosen by the audience",
		amount: 4500000,
	},
	{
		city: "Istanbul",
		country: "Turkey",
		imageUrl: "/images/istanbul-turkey.jpg",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 6500000,
	},
	{
		city: "London",
		country: "UK",
		imageUrl: "/images/london_uk.webp",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 2500000,
	},
	{
		city: "Montmarte",
		country: "France",
		imageUrl: "/images/montmarte-france.jpg",
		rating: 4,
		text: "Visiting the best tourist areas chosen by the audience",
		amount: 4500000,
	},
	{
		city: "Istanbul",
		country: "Turkey",
		imageUrl: "/images/istanbul-turkey.jpg",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 6500000,
	},
	{
		city: "London",
		country: "UK",
		imageUrl: "/images/london_uk.webp",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 2500000,
	},
];

export const apartments: ApartmentTypes[] = [
	{
		amount: 65,
		city: "Kensignton",
		country: "London",
		rating: 5,
		imageUrl: "",
		name: "7Seasons Apartments",
	},
	{
		amount: 65,
		city: "Hungary",
		country: "Budapest",
		rating: 5,
		imageUrl: "",
		name: "Along with the villa",
	},
	{
		amount: 65,
		city: "Williamstreet",
		country: "Boxon",
		rating: 5,
		imageUrl: "",
		name: "Resort and Recreation",
	},
	{
		amount: 65,
		city: "Citadines Opera Paris",
		country: "France",
		rating: 5,
		imageUrl: "",
		name: "Beautiful and Classy",
	},
	{
		amount: 65,
		city: "Sugar Apartments",
		country: "Brazil",
		rating: 5,
		imageUrl: "",
		name: "Permanent Peace",
	},
];
