import { ApartmentTypes } from "@/interface/apartments";
import { DestinationType } from "@/interface/destination";

export const destinations: DestinationType[] = [
	{
		city: "Montmarte",
		country: "France",
		imageUrl:
			"https://cdn.contexttravel.com/image/upload/w_1500,q_60/v1558551574/blog/Things%20Didn%27t%20Know%20About%20Montmartre/john-towner-125993-unsplash_1_1024x768.jpg",
		rating: 4,
		text: "Visiting the best tourist areas chosen by the audience",
		amount: 4500000,
	},
	{
		city: "Istanbul",
		country: "Turkey",
		imageUrl: "/images/istanbul-turkey.jpg",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 6500000,
	},
	{
		city: "London",
		country: "UK",
		imageUrl: "/images/london_uk.webp",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 2500000,
	},
	{
		city: "Montmarte",
		country: "France",
		imageUrl: "/images/montmarte-france.jpg",
		rating: 4,
		text: "Visiting the best tourist areas chosen by the audience",
		amount: 4500000,
	},
	{
		city: "Istanbul",
		country: "Turkey",
		imageUrl: "/images/istanbul-turkey.jpg",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 6500000,
	},
	{
		city: "London",
		country: "UK",
		imageUrl: "/images/london_uk.webp",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 2500000,
	},
	{
		city: "Montmarte",
		country: "France",
		imageUrl: "/images/montmarte-france.jpg",
		rating: 4,
		text: "Visiting the best tourist areas chosen by the audience",
		amount: 4500000,
	},
	{
		city: "Istanbul",
		country: "Turkey",
		imageUrl: "/images/istanbul-turkey.jpg",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 6500000,
	},
	{
		city: "London",
		country: "UK",
		imageUrl: "/images/london_uk.webp",
		rating: 5,
		text: "One of our best-selling tours to Turkey and visiting it's regions ",
		amount: 2500000,
	},
];

export const apartments: ApartmentTypes[] = [
	{
		amount: 65,
		city: "Kensignton",
		country: "London",
		rating: 5,
		imageUrl: "/images/hotel 1.jpg",
		name: "7Seasons Apartments",
	},
	{
		amount: 65,
		city: "Hungary",
		country: "Budapest",
		rating: 5,
		imageUrl: "/images/hotel 2.jpg",
		name: "Along with the villa",
	},
	{
		amount: 65,
		city: "Williamstreet",
		country: "Boxon",
		rating: 5,
		imageUrl: "/images/hotel 3.jpg",
		name: "Resort and Recreation",
	},
	{
		amount: 65,
		city: "Citadines Opera Paris",
		country: "France",
		rating: 5,
		imageUrl: "/images/hotel 4.jpg",
		name: "Beautiful and Classy",
	},
	{
		amount: 65,
		city: "Sugar Apartments",
		country: "Brazil",
		rating: 5,
		imageUrl: "/images/hotel 5.jpg",
		name: "Permanent Peace",
	},
];
